
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelManagmentSystem.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_room
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_room()
    {

        this.tbl_booking = new HashSet<tbl_booking>();

    }


    public int room_id { get; set; }

    public string room_number { get; set; }

    public int room_type_id { get; set; }

    public int booking_status_id { get; set; }

    public Nullable<bool> is_Active { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_booking> tbl_booking { get; set; }

    public virtual tbl_booking_status tbl_booking_status { get; set; }

    public virtual tbl_room_type tbl_room_type { get; set; }

}

}
